export const resource = {
  VN: {
    ToastMessage: {
      CannotGetLicensePlate: {
        Icon: "mdi mdi-alert",
        IconColor: "rgb(244, 147, 66)",
        Status: "Lỗi!",
        TextClass: "text-error",
        Desc: "Không thể xử lý hình ảnh để lấy biển số xe. Vui lòng thử lại!",
        OptionAction: "",
      },
      ExistVehicleInGarage: {
        Icon: "mdi mdi-alert",
        IconColor: "rgb(244, 147, 66)",
        Status: "Lỗi!",
        TextClass: "text-error",
        Desc: "Xe này hiện đang có trong bãi đỗ xe. Vui lòng kiểm tra lại!",
        OptionAction: "",
      },
      CannotGetParkSlots: {
        Icon: "mdi mdi-alert",
        IconColor: "rgb(244, 147, 66)",
        Status: "Lỗi!",
        TextClass: "text-error",
        Desc: "Không thể lấy thông tin bãi đỗ xe. Vui lòng thử lại!",
        OptionAction: "",
      },
      VehicleOutSuccess: {
        Icon: "mdi mdi-check-circle",
        IconColor: "#50b83c",
        Status: "Thành công!",
        TextClass: "text-50b83c",
        Desc: "Lấy xe ra khỏi bãi thành công.",
        OptionAction: "",
      },

      VehicleOutDateNotLessThenCreatedDate: {
        Icon: "mdi mdi-alert",
        IconColor: "rgb(244, 147, 66)",
        Status: "Lỗi!",
        TextClass: "text-error",
        Desc: "Thời điểm xe ra không thể nhỏ hơn hoặc bằng thời điểm xe vào!",
        OptionAction: "",
      },
      VehicleOutDateNotEnter: {
        Icon: "mdi mdi-alert",
        IconColor: "rgb(244, 147, 66)",
        Status: "Lỗi!",
        TextClass: "text-error",
        Desc: "Bạn chưa nhập thời gian xe ra!",
        OptionAction: "",
      },
      LicesePlateNotEnter: {
        Icon: "mdi mdi-alert-circle-outline",
        IconColor: "red",
        Status: "Lỗi!",
        TextClass: "text-[red]",
        Desc: "Bạn chưa nhập thông tin hình ảnh của xe.",
        OptionAction: "",
      },
      LicesePlateNotCheck: {
        Icon: "mdi mdi-alert-circle-outline",
        IconColor: "red",
        Status: "Lỗi!",
        TextClass: "text-[red]",
        Desc: "Bạn chưa kiểm tra thông tin hình ảnh của xe.",
        OptionAction: "",
      },
      CheckLisensePlateSuccess: {
        Icon: "mdi mdi-check-circle",
        IconColor: "#50b83c",
        Status: "Chính xác!",
        TextClass: "text-50b83c",
        Desc: "Biển số xe vào và xe ra trùng khớp.",
        OptionAction: "",
      },
      ImageNotInclueVehicle: {
        Icon: "mdi mdi-alert",
        IconColor: "rgb(244, 147, 66)",
        Status: "Lỗi!",
        TextClass: "text-error",
        Desc: "Hình ảnh không có thông tin biển số xe. Vui lòng sử dụng hình ảnh khác!",
        OptionAction: "",
      },
      EnterImageHasOneLicensePlate: {
        Icon: "mdi mdi-alert",
        IconColor: "rgb(244, 147, 66)",
        Status: "Hình ảnh không hợp lệ!",
        TextClass: "text-error",
        Desc: "Vui lòng chọn hoặc chỉnh sửa để có hình ảnh chỉ có một biển số xe.",
        OptionAction: "",
      },
      CannotCreateParkingHistory: {
        Icon: "mdi mdi-alert",
        IconColor: "rgb(244, 147, 66)",
        Status: "Lỗi!",
        TextClass: "text-error",
        Desc: "Không thể thêm xe vào bãi. Vui lòng thử lại.",
        OptionAction: "",
      },
      EnterVehicleSuccess: {
        Icon: "mdi mdi-check-circle",
        IconColor: "#50b83c",
        Status: "Thành công!",
        TextClass: "text-50b83c",
        Desc: "Thêm xe vào bãi thành công.",
        OptionAction: "Hoàn tác",
      },
      CannotCreateOne: {
        Icon: "mdi mdi-alert",
        IconColor: "rgb(244, 147, 66)",
        Status: "Lỗi!",
        TextClass: "text-error",
        Desc: "Không thể tạo mới một nhân viên!",
        OptionAction: "",
      },
      DeleteEmployeeFailed: {
        Icon: "mdi mdi-alert-circle-outline",
        IconColor: "red",
        Status: "Thất bại!",
        TextClass: "text-[red]",
        Desc: "Xóa thông tin nhân viên không thành công!",
        OptionAction: "",
      },
      CannotExportExcel: {
        Icon: "mdi mdi-alert-circle-outline",
        IconColor: "red",
        Status: "Thất bại!",
        TextClass: "text-[red]",
        Desc: "Không thể xuất thông tin nhân viên ra file Excel! Vui lòng thử lại hoặc liên hệ chúng tôi để được hỗ trợ.",
        OptionAction: "",
      },
      CannotGetNewEmployeeCode: {
        Icon: "mdi mdi-alert-circle-outline",
        IconColor: "red",
        Status: "Thất bại!",
        TextClass: "text-[red]",
        Desc: "Không thể lấy mã nhân viên mới.",
        OptionAction: "",
      },
      VehicleInFifferenceVehicleOut: {
        Icon: "mdi mdi-alert-circle-outline",
        IconColor: "red",
        Status: "Lỗi!",
        TextClass: "text-[red]",
        Desc: "Biển số xe vào và xe ra khác nhau. Vui lòng kiểm tra lại",
        OptionAction: "",
      },
      DeleteParkMemberFailed: {
        Icon: "mdi mdi-alert-circle-outline",
        IconColor: "red",
        Status: "Lỗi!",
        TextClass: "text-[red]",
        Desc: "Không thể xóa một khách hàng.",
        OptionAction: "",
      },
      CannotGetParkMemberData: {
        Icon: "mdi mdi-alert-circle-outline",
        IconColor: "red",
        Status: "Lỗi!",
        TextClass: "text-[red]",
        Desc: "Không thể lấy thông tin khách hàng.",
        OptionAction: "",
      },
    },
    Dialog: {
      ConfirmCreateParkMember: {
        Title: "Tạo mới một khách hàng",
        Icon: "icon__bigwarning",
        Message: "Bạn có chắc chắn muốn tạo mới một khách hàng?",
      },
      EmptyField: (missingInputMessage) => ({
        Title: "Trường thông tin bắt buộc nhập",
        Icon: "icon__bigwarning",
        Message: missingInputMessage,
      }),
    },
  },
};
